# Generated by Django 5.0.2 on 2024-02-08 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("born_date", models.DateField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, max_length=400, null=True)),
                ("work", models.CharField(blank=True, max_length=40, null=True)),
                ("school", models.CharField(blank=True, max_length=40, null=True)),
                ("passion", models.CharField(blank=True, max_length=40, null=True)),
                ("fun_fact", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "favourite_song",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("book_title", models.CharField(blank=True, max_length=40, null=True)),
                ("pets", models.CharField(blank=True, max_length=40, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "languages",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="profiles",
                        to="users.language",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
