# Generated by Django 5.0.2 on 2024-02-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_language_profilelanguages_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="languages",
        ),
        migrations.DeleteModel(
            name="ProfileLanguages",
        ),
        migrations.AddField(
            model_name="profile",
            name="languages",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
