# Generated by Django 5.0.2 on 2024-02-08 22:48

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_profile_languages_delete_profilelanguages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=users.models.get_user_media_direction
            ),
        ),
    ]
