# Generated by Django 5.0.2 on 2024-02-08 23:57

import django.core.validators
import django.db.models.deletion
import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("users", "0004_profile_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                (
                    "check_in",
                    models.CharField(
                        choices=[
                            ("Independent", "Independent"),
                            ("Meeting", "Meeting"),
                        ],
                        max_length=20,
                    ),
                ),
                ("guests_count", models.PositiveIntegerField(default=1)),
                ("beds_count", models.PositiveIntegerField(default=1)),
                ("toilets_count", models.PositiveIntegerField(default=1)),
                ("description", models.TextField()),
                ("parking", models.BooleanField(default=False)),
                ("pool", models.BooleanField(default=False)),
                ("pets", models.BooleanField(default=False)),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cities_light.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cities_light.country",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=listings.models.get_listing_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpeg", "jpg"]
                            )
                        ],
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                    ),
                ),
            ],
        ),
    ]
