# Generated by Django 5.0.2 on 2024-02-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_rename_images_listingimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listingimage",
            name="listing",
        ),
        migrations.AddField(
            model_name="listing",
            name="images",
            field=models.ManyToManyField(to="listings.listingimage"),
        ),
    ]
