# Generated by Django 5.0.2 on 2024-02-09 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_remove_listingimage_listing_listing_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="images",
        ),
        migrations.AddField(
            model_name="listingimage",
            name="listing",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="listings.listing",
            ),
            preserve_default=False,
        ),
    ]
