# Generated by Django 5.0.2 on 2024-02-09 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_remove_listing_images_listingimage_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listingimage",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="listings.listing",
            ),
        ),
    ]
