# Generated by Django 5.0.2 on 2024-02-09 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_alter_listingimage_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listingimage",
            name="listing",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="listings.listing",
            ),
        ),
    ]
